### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by sardar97** [Sysinfocus/simple-ui#3]
please care about RTL support for all components.

**Comment by Sysinfocus** [comment]
Yes, RTL support is already in the checklist and will be progressively in the upcoming releases.

**Comment by sardar97** [comment]
> Yes, RTL support is already in the checklist and will be progressively in the upcoming releases.

That's good , are there any road map ? Especially about DataGrid Component I believe in your component named DataTable.
which is the most important Component for developers.

**Comment by Sysinfocus** [comment]
We will update this repo once the RTL support is added. Keep an eye on future releases. Thanks.
